# Configuración de PostgreSQL
spring:    
  datasource:    
    url: jdbc:postgresql://localhost:5432/react        
    username: postgres        
    password: 12345678    
  jpa:        
    hibernate:        
      ddl-auto: update        
    dialect: org.hibernate.dialect.PostgreSQLDialect        
    show-sql: true    
  main: 
    lazy-initialization: true    
  devtools:     
    restart: 
      poll-interval: 4s       
    quiet-period: 3s  
  #data:
  # rest:  
  #   base-path: /api
